name: 'Check spelling'
on: # rebuild any PRs and main branch changes
  pull_request:

jobs:
  spellcheck: # run the action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: streetsidesoftware/cspell-action@v1.3.5
        with:
          inline: warning
          strict: false
          incremental_files_only: true
