name: 'Check spelling'
on: # rebuild any PRs and main branch changes
  pull_request:
    branches-ignore:
      - "dependabot/**"

env:
  FORCE_COLOR: 2
  NODE: 16

permissions:
  contents: read

jobs:
  spellcheck: # run the action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@v2
        with:
          inline: warning
          strict: false
          incremental_files_only: true
